name: CI

on:
  push:
    branches: [main]

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: shopify-store-locator-300908
      RUN_REGION: europe-west1
      SERVICE_NAME: instagram-scraper
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Setup GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "286.0.0"
          service_account_email: ${{ secrets.RUN_SA_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: shopify-store-locator-300908
      - name: Build Docker Image
        run: docker build . -t "eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
      - name: Authenticate for gcr
        run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io/$PROJECT_ID
      - name: Push Docker Image to gcr
        run: docker push eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
      - name: Deploy
        run: |-
          gcloud run deploy $SERVICE_NAME \
            --quiet \
            --region $RUN_REGION \
            --image eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --platform managed \
            --allow-unauthenticated
